### ISSUE TITLE
table里面有文本框，文本框里面的值不显示

### ISSUE THREAD

**Issue by hulang** [Sight-wcg/layui-theme-dark#11]
![px](https://github.com/Sight-wcg/layui-theme-dark/assets/4961831/39eb9bb5-6fb7-4e60-96fd-3afd00aea275)

希望适配下。。。最新`layui 2.9.13`

**Comment by Sight-wcg** [comment]
应该是其他自定义样式影响了，开发者工具中检查一下。

**Comment by hulang** [comment]
明白了。是我自定义的文本框问题。
