### ISSUE TITLE
浅色导航菜单类样式

### ISSUE THREAD

**Issue by luoxing66** [Sight-wcg/layui-theme-dark#5]
我在导航菜单添加样式layui-bg-gray之后，当开启深色模式，依旧是浅色的，我查看元素发现layui-bg-gray使用了!important，所以建议在深色模式下也加上!important

**Comment by Sight-wcg** [comment]
nav-menu 在 bg-gray 下有个左边距，深色下表现不太好，可以自行处理下
![image](https://github.com/Sight-wcg/layui-theme-dark/assets/26325820/09836268-df8b-4552-a1bb-51adcf1bfd6f)
![image](https://github.com/Sight-wcg/layui-theme-dark/assets/26325820/71e90640-bee4-4d02-ad95-5f1625ac41d5)
